
### --- Custom aliases:
alias l='ls -ltrh'
alias emacs='emacs &'
alias c='clear'
alias jup='jupyter notebook &'
alias subl='/home/razielar/bin/sublime_text_3/sublime_text &'
alias pycharm='/home/razielar/bin/pycharm-2019.3.3/bin/pycharm.sh &'

#Prompt configuration
#New Prompt configuration:
export PS1="\[\033[01;32m\]\u\[\033[01;m\]@\[\033[01;36m\]\h: \[\033[31m\]\W\[\033[m\]\$ "













